### ISSUE TITLE
Consider web harvesting failures

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#616]
Currently, all failures by heritrix to retrieve web seeds are ignored.  In general, this is acceptable as failures are to be expected.  However, this masks when there is an actual problem which is causing web harvesting to fail.

Perhaps thresholds for reporting back warning or error messages might be appropriate.

**Comment by justinlittman** [comment]
This is suspicious:  http://gwsfm-prod2.wrlc.org/ui/collections/16/

Why are there always 8 resources?

**Comment by Tanych** [comment]
@justinlittman  It could something wrong with the counter. When I dig into the web warc file, it actually has more than 8 web resources archived successfully.  I will try to figure it out.

**Comment by Tanych** [comment]
when I testing locally, the counter seems work well, It might be special case running on production.

**Comment by Tanych** [comment]
@justinlittman all the web harvester for weibo harvester has the same seeds start at `20161201162305`.

**Comment by Tanych** [comment]
@justinlittman 
All the web harvesters in the production instance have the same seeds after some time point, including some twitter web harvesters. 
The Weibo or twitter harvests actually get the correct URL seeds to the URL list, the web harvester doesn't deal well with these seeds. 
Try to restart `sfm_webharvester_1` and `sfm_heritrix_1`, now the web harvest pending on `requested`.  Not sure what's going wrong with the web harvester. I didn't restart all containers since it might cause other troubles. I can talk to you in the office tomorrow.

**Comment by Tanych** [comment]
@justinlittman 
More information about the same seeds problems of web harvester.
### Checking exist collection

#### Web harvester Rabbit Queue
* stop web harvester and heritrix container, get message manual  with Rabbit admin.
Message:
```json
{"collection_set": {"id": "40c02df38fc44b12bd3f8dedb1948999"}, "collection": {"id": "ecd1e90830124697a6d4f9b6dbd614a0"}, "parent_id": "543f2ab524c34545898fb49ba3d83284", "seeds": 
[{"token": "http://wx2.sinaimg.cn/bmiddle/61add7e3ly1fdq8xeleu6j21933x6npd.jpg"}, 
{"token": "http://t.cn/Rikyiba"}, 
{"token": "http://wx2.sinaimg.cn/thumbnail/61add7e3ly1fdq8xeleu6j21933x6npd.jpg"}, 
{"token": "http://t.cn/R6PG91S"}, 
{"token": "http://wx2.sinaimg.cn/large/61add7e3ly1fdq8xeleu6j21933x6npd.jpg"}, 
{"token": "http://t.cn/R6PUe44"}], 
"path": "/sfm-data/collection_set/40c02df38fc44b12bd3f8dedb1948999/ecd1e90830124697a6d4f9b6dbd614a0", "type": "web", "id": "883a1077ef4540ed8eac267e8e46e438"}
```

#### Heritrix seeds 
* start the heritrix and web harvester 

![heritix_seed_log](https://cloud.githubusercontent.com/assets/3956411/24052207/0962b59e-0b0b-11e7-9db2-a8ca25cd2314.png)

The seeds are different from the message seeds. They are the same seeds for the several months. 
So, the message queue can get the right seeds, but the heritrix are always doing the same seeds. 

### Building new collection
The heritrix can do it in the right way.

**Comment by Tanych** [comment]
The web harvester write the correct seeds to the work_path. I am not sure where the heritrix get the old repeat seeds.

**Comment by justinlittman** [comment]
Another repeating failure: http://gwsfm-sandbox.wrlc.org/ui/harvests/1250/

**Comment by Tanych** [comment]
@justinlittman 
The path of seeds in `crawler-beans.cxml` for heritrix_job doesn't update when the web harvester work path has changed due to rebuild or something else. 
The sfm_heritrix always get the seeds from the old work path.  The old work path doesn't have any update seeds so it always collecting the same seed.

**Comment by Tanych** [comment]
@justinlittman 
With fresh air and fresh mind when proceeding--:

To replicate the heritrix repeated seeds problem in dev mode:
### Part I Initial Job
1. build a twitter user_timeline **uncheck** the `incremental`, to make sure we can do several tests attempts, like this:

* [ ] Incremental harvest
* [x] Media (e.g., images) embedded in tweets.
* [x] User profile images and user banner images.
* [ ] Web pages referenced in tweets.

2. add seed `SocialFeedMgr` 
3. Turn on the collection and waiting the collection complete
4. check the collection `crawler-beans.cxml`  file and the path of seeds.txt
```
 <property name="path" value="/sfm-data/containers/ad0362dbf70f/seeds.txt" />
```
5. check the `seeds.txt` at the heritrix_job location
```
 /sfm-data/collection_set/c30493ec841e44c38eaaf8c77a1f52b0/2ba4561cebd04dc2bebf39c6d51fb007/heritrix_job/20170323205055
```

6.it should be the seeds

```
http://abs.twimg.com/images/themes/theme1/bg.png
http://pbs.twimg.com/media/CtW4AliWAAEY1b4.jpg
http://pbs.twimg.com/profile_images/715244604061261824/s8B16sza_normal.jpg
http://pbs.twimg.com/media/C5Xsin3VcAA_HdN.jpg
http://pbs.twimg.com/media/CtW4AlhWgAAYC1U.jpg
http://pbs.twimg.com/media/CvSR2-3WEAAJ-aR.jpg
http://pbs.twimg.com/media/ClBBdKMWAAEDws1.jpg
http://pbs.twimg.com/media/ClAePqtW0AYP5Yd.jpg
http://pbs.twimg.com/media/ClBBcF_WIAAVCbq.jpg
http://pbs.twimg.com/media/ClAbZVHWYAATBDA.jpg
http://pbs.twimg.com/media/ClFLht7UoAAzyTr.jpg
http://pbs.twimg.com/media/CtW4AlfWgAIIlKQ.jpg
http://pbs.twimg.com/media/ClBBeKwWYAEOplx.jpg
http://pbs.twimg.com/media/C109SFEXEAAHzeW.jpg
http://pbs.twimg.com/media/CtW4AlaWIAAbw3v.jpg
```
This part makes senses.

### Part II Rebuild web harvester
1. kill the web harvester container
```
docker kill sfm_web_harverter
```
2. remove the volume of web harvester or remove the image to rebuild, it will make the web harvester has a different work path.
```
docker rm -v --force sfm_web_harverter
```
3. start the sfm_web_harverter
```
docker start sfm_web_harverter
```
The seeds path has changed when it shows on debug log of the initiation of web harvester. It could be:
```
 <property name="path" value="/sfm-data/containers/780623e347ca/seeds.txt" />
```
4.Turn off the collection and make some edits, only collect the profile image like:

* [ ] Incremental harvest
* [ ] Media (e.g., images) embedded in tweets.
* [x] User profile images and user banner images.
* [ ] Web pages referenced in tweets.

5. turn on the collection  and waiting complete collecting.
6. the web harvester writes seeds at `/sfm-data/containers/780623e347ca/seeds.txt`, it should be:
```
http://abs.twimg.com/images/themes/theme1/bg.png
http://pbs.twimg.com/profile_images/715244604061261824/s8B16sza_normal.jpg
```
7. check the collection `crawler-beans.cxml`  file, the seeds path still be the old path
```
 <property name="path" value="/sfm-data/containers/ad0362dbf70f/seeds.txt" />
```
8. the `seeds.txt` for the collection still be the old:
```
http://abs.twimg.com/images/themes/theme1/bg.png
http://pbs.twimg.com/media/CtW4AliWAAEY1b4.jpg
http://pbs.twimg.com/profile_images/715244604061261824/s8B16sza_normal.jpg
http://pbs.twimg.com/media/C5Xsin3VcAA_HdN.jpg
http://pbs.twimg.com/media/CtW4AlhWgAAYC1U.jpg
http://pbs.twimg.com/media/CvSR2-3WEAAJ-aR.jpg
http://pbs.twimg.com/media/ClBBdKMWAAEDws1.jpg
http://pbs.twimg.com/media/ClAePqtW0AYP5Yd.jpg
http://pbs.twimg.com/media/ClBBcF_WIAAVCbq.jpg
http://pbs.twimg.com/media/ClAbZVHWYAATBDA.jpg
http://pbs.twimg.com/media/ClFLht7UoAAzyTr.jpg
http://pbs.twimg.com/media/CtW4AlfWgAIIlKQ.jpg
http://pbs.twimg.com/media/ClBBeKwWYAEOplx.jpg
http://pbs.twimg.com/media/C109SFEXEAAHzeW.jpg
http://pbs.twimg.com/media/CtW4AlaWIAAbw3v.jpg
```
The seeds mismatched since the work path of web harvester has changed. However, the new `crawler-beans.cxml`  file doesn't submit for all the collection. They all keep the old one.

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/sfm-web-harvester/pull/9
